import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import joblib  # To save the scaler
import os
from model import LSTMAutoencoder  # Import the class we defined earlier
from preprocessing import preprocess_data  # Week 5: Import our clean pipeline

# --- CONFIGURATION ---
SEQ_LENGTH = 30
FEATURES = 2  # Temperature, Vibration (used by LSTM windowing)
EMBEDDING_DIM = 64
EPOCHS = 100
LR = 0.001
CSV_PATH = "normal_training_data.csv"  # Generated by Vineet's simulator


# --- STEP 1: LOAD OR GENERATE DATA ---
def load_training_data():
    """
    Week 5 Task 2: Load CSV of normal sensor data and feed it through
    the preprocess_data pipeline. Falls back to synthetic generation
    if the CSV isn't available yet.
    """
    if os.path.exists(CSV_PATH):
        print(f"Loading training data from {CSV_PATH}...")
        df = pd.read_csv(CSV_PATH)

        # --- Week 5 Pipeline: Preprocess via the clean function ---
        # This also saves scaler.save automatically
        if 'pressure' in df.columns:
            data_list = df[['temperature', 'vibration', 'pressure']].to_dict('records')
            scaled_3f = preprocess_data(data_list)
            print(f"  ✅ preprocess_data() scaled {len(scaled_3f)} rows (3 features)")
            print(f"  ✅ scaler.save written by preprocess_data()")

        # For LSTM training we use the 2-feature version (temperature, vibration)
        return df
    else:
        print(f"⚠️  {CSV_PATH} not found – generating synthetic data instead.")
        return generate_fake_data()


# --- FALLBACK: GENERATE SYNTHETIC DATA ---
def generate_fake_data(n_samples=3000):
    t = np.linspace(0, 100, n_samples)

    # Feature 1: Vibration (Periodic Sine Wave)
    vibration = np.sin(t)

    # Feature 2: Temperature (Slowly varying + slight noise)
    temperature = np.linspace(20, 30, n_samples) + np.random.normal(0, 0.5, n_samples)

    df = pd.DataFrame({'temperature': temperature, 'vibration': vibration})
    return df

# --- STEP 2: PREPROCESSING ---
print("Loading and processing data...")
df = load_training_data()

# Normalize to [0, 1] (2-feature version for LSTM)
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(df[['temperature', 'vibration']])

# Create Sliding Windows (3D Tensor)
def create_sequences(data, seq_length):
    xs = []
    for i in range(len(data) - seq_length):
        x = data[i:(i + seq_length)]
        xs.append(x)
    return np.array(xs)

X_train = create_sequences(data_scaled, SEQ_LENGTH)

# Convert to PyTorch Tensor
# Shape: (Samples, 30, 2)
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)

# --- STEP 3: INITIALIZE MODEL ---
model = LSTMAutoencoder(seq_length=SEQ_LENGTH, n_features=FEATURES, embedding_dim=EMBEDDING_DIM)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

# --- STEP 4: TRAINING LOOP ---
print("Starting training...")
model.train()
for epoch in range(EPOCHS):
    optimizer.zero_grad()
    
    # Forward pass: Try to reconstruct the input
    output = model(X_train_tensor)
    
    # Calculate Loss: Difference between Input and Reconstruction
    loss = criterion(output, X_train_tensor)
    
    # Backward pass
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{EPOCHS}], Loss: {loss.item():.6f}')

# --- STEP 5: CALCULATE THRESHOLD ---
# We check how bad the error is on "normal" data. 
# The max error on normal data becomes our limit for anomalies.
print("Calculating anomaly threshold...")
model.eval()
with torch.no_grad():
    reconstructions = model(X_train_tensor)
    # Calculate Mean Squared Error per sequence
    loss_per_sequence = torch.mean((X_train_tensor - reconstructions)**2, dim=[1, 2])
    
    # Set threshold to the max loss seen during training (plus a tiny buffer)
    threshold = torch.max(loss_per_sequence).item()

print(f"Training Complete. Max Normal Loss (Threshold): {threshold:.6f}")

# --- STEP 6: SAVE ARTIFACTS ---
# 1. Save the Model Weights
torch.save(model.state_dict(), 'lstm_autoencoder.pth')
# 2. Save the Scaler (Crucial for preprocessing new data identically)
joblib.dump(scaler, 'scaler.save')
# 3. Save the Threshold (Simple text file)
with open('threshold.txt', 'w') as f:
    f.write(str(threshold))

print("Model, Scaler, and Threshold saved successfully.")